version: "3.9"
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    restart: always
    ports:
      - "2717:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: adrien
      MONGO_INITDB_ROOT_PASSWORD: franto
      MONGO_INITDB_ROOT_DATABASE: etudiant-service
    volumes:
      - ./data:/data/db

  etudiant-service:
    build: .
    container_name: etudiant-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

